[omxh264enc]
type-name=GstOMXH264Enc
core-name=/usr/lib/libomxr_core_x5h.so
component-name=OMX.RENESAS.VIDEO.ENCODER.H264
rank=256
in-port-index=0
out-port-index=1
hacks=no-disable-outport;renesas-encmc-stride-align
sink-template-caps=video/x-raw,format=(string){NV12,I420},width=(int)[80,3840],height=(int)[80,2160]
src-template-caps=video/x-h264,stream-format=(string)byte-stream,width=(int)[80,3840],height=(int)[80,2160]


