PREFERRED_VERSION_virglrenderer = "1.0.1"

PREFERRED_VERSION_qemu = "9.1.1"
PREFERRED_VERSION_qemu-native = "9.1.1"
PREFERRED_VERSION_qemu-system-native = "9.1.1"
PREFERRED_VERSION_qemu-helper-native = "1.0"
PREFERRED_VERSION_nativesdk-qemu-helper = "1.0"
PREFERRED_VERSION_qemuwrapper-cross = "1.0"
