#@TYPE: Machine
#@NAME: Ironhide machine
#@DESCRIPTION: Machine configuration for running Ironhide

SOC_FAMILY = "r8a78000"

DEFAULTTUNE ?= "aarch64"
require conf/machine/include/arm/arch-arm64.inc
require conf/machine/include/rcar-gen5-common.inc

# Device tree for Ironhide
#KERNEL_DEVICETREE = " \
#    renesas/r8a779g0-whitehawk.dtb \
#    renesas/r8a779g0-whitehawk-native.dtb \
#"

# Ironhide u-boot configure
UBOOT_CONFIG ??= "x5h"
UBOOT_CONFIG[x5h] = "rcar-x5h_board_defconfig"
