#@TYPE: Machine
#@NAME: ironhide machine
#@DESCRIPTION: Machine configuration for running Ironhide

SOC_FAMILY = "r8a78000"

DEFAULTTUNE ?= "aarch64"
require conf/machine/include/arm/arch-arm64.inc
require conf/machine/include/rcar-gen5-common.inc

# Device tree for Ironhide
KERNEL_DEVICETREE = "renesas/r8a78000-ironhide.dtb"

# X5H u-boot configure
UBOOT_CONFIG ??= "ironhide"
UBOOT_CONFIG[ironhide] = "r8a78000_ironhide_defconfig"

EXTRA_IMAGEDEPENDS += "arm-trusted-firmware optee-os"

