#@TYPE: Machine
#@NAME: ironhide machine
#@DESCRIPTION: Machine configuration for running Ironhide

SOC_FAMILY = "r8a78000-evb"

require conf/machine/include/rcar-gen5-evb.inc

UBOOT_CONFIG = "ironhide"

KERNEL_DEVICETREE = "${KERNEL_DEVICETREE_IRONHIDE}"
