#@TYPE: Machine
#@NAME: perceptor machine
#@DESCRIPTION: Machine configuration for running Perceptor

SOC_FAMILY = "r8j78070-evb"

require conf/machine/include/rcar-gen5-evb.inc

UBOOT_CONFIG = "perceptor"

KERNEL_DEVICETREE = "${KERNEL_DEVICETREE_PERCEPTOR}"

SECURITY_BSP_MACHINE = "perceptor"
