#@TYPE: Machine
#@NAME: x5h machine
#@DESCRIPTION: Machine configuration for running X5H

SOC_FAMILY = "x5h"

DEFAULTTUNE ?= "aarch64"
require conf/machine/include/arm/arch-arm64.inc
require conf/machine/include/rcar-gen5-common.inc

# Device tree for X5H
KERNEL_DEVICETREE = " \
    renesas/r8a78000-rfs2x.dtb \
    renesas/r8a78000-rfs2x-uio.dtb \
"

# X5H u-boot configure
UBOOT_CONFIG ??= "x5h"
UBOOT_CONFIG[x5h] = "r8a78000_ironhide_defconfig"

BBMASK += "meta-renesas/meta-rcar-gen5/recipes-core/busybox/"

# Use Poky default util-linux version instead of custom 2.41
PREFERRED_VERSION_util-linux = "2.39.3"
